#!/usr/bin/env bash
set -e

pushd "$(dirname "$0")" >/dev/null

if [ ! -d ".venv" ]; then
    python3 -m venv .venv
fi

source .venv/bin/activate
if [ -z "$TM_NO_INSTALL" ]; then
    pip install -r requirements.txt || echo "pip install failed, continuing"
fi

popd >/dev/null